# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38446844dd86d8770c7650620ef7cc973c28207d3bbba575561555e4020133b96d795b46481edf096f77e7a788176fb5c89ed988ff1fe45c23b7dcc022fd5730

test:
  secret_key_base: ab40a46195321d62ff0c8afbb31e5f9bb20af48b968107a1435465998a5dbc910641be9b90adac6025ffdb1f0db5f3681424f565e86bf348e689596bb0da0d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
